language: node_js
node_js:
  - "node"

branches:
  only:
  - continuous-integration/travis-ci

before_install:
  - npm run bootstrap

script:
  - npm run test
  - npm run lint
  - npm run format

after_script:
  - npm run test-publish-coverage
  - bash .travis/push.sh

after_success:
  - npm run semantic-release
